### PR TITLE
Develop 2 1

### PR DESCRIPTION
**Pull request by gsteward**

### CODE REVIEW

**Comment by pannal** [comment]
What is this?

**Comment by pannal** [comment]
Enlighten me, until then: closing the PR. 2.1 will come soon.

**Comment by gsteward** [comment]
My apologies.
This should not have occurred.

-Greg

**Comment by pannal** [comment]
What exactly lead to this? :D

**Comment by gsteward** [comment]
Frankly, I’m not really sure.
I am somewhat new to github.
I have github for desktop installed and checked out the project to have it download.
Maybe I am not doing something right.
I must have changed something and did a commit.  Not really sure.
Will be more careful going forward.

Again, my apologies,
-Greg

**Comment by pannal** [comment]
Nah, all good! I just never came across such a pull request :)

**Pull request closed without merging**
