### PR TITLE
Add Hungarian provider Hosszupuska

### PR DESCRIPTION
**Pull request by morpheus133**
link: http://hosszupuskasub.com/

### CODE REVIEW

**Comment by pannal** [comment]
Thanks. A couple of questions:

- Why the require(lxml)? The PMS infrastructure already supplies lxml.
- You should consider using the mixin `subliminal_patch.providers.mixins.ProviderSubtitleArchiveMixin` and use `self.get_subtitle_from_archive()` to extract the requested subtitle from the zip archive.

**Comment by morpheus133** [comment]
Answer to both:
I also create this provider to Subliminal and try to have as minimal different as possible:
https://github.com/Diaoul/subliminal/pull/809

- require(lxml)
For subliminal  I need to support also html_parser not just lxml, and this was left here. (I can remove becuse here it is not neceserry)
-mixin
I will check this and add it.

**Comment by morpheus133** [comment]
I checked all your comments and implemented them.

**Comment by pannal** [comment]
Great, for that to work your Subtitle subclass needs to implement the attributes `releases` and `asked_for_episode`, though.

**Comment by morpheus133** [comment]
What is the difference between subtitle.asked_for_episode and subtitle. episode?
At the other providers it seems the same. Or I missed something?

**Comment by pannal** [comment]
`Subtitle.episode` should be the episode returned by the provider, not the one searched for, to circumvent bad matches. `asked_for_episode` should be the one that was searched for.

**Comment by morpheus133** [comment]
I made all the modification, you mentioned.

**Comment by pannal** [comment]
Great, thank you!

**Pull request merged**
