### PR TITLE
Update common.py

### PR DESCRIPTION
**Pull request by doopler**

### CODE REVIEW

**Comment by pannal** [comment]
Can you give me an example of when this comes in effect?

**Comment by doopler** [comment]
this reverses also other punctuation marks like (,)(')(:)(-)
i added this on my system and it's seems to work so far.
if i did something wrong in the code please tell me ( i'm not a coder)

**Comment by pannal** [comment]
Should be fine, as those still are only at the "beginning" of a sentence.

**Comment by doopler** [comment]
Ok.
Thank you.

**Pull request merged**
