### PR TITLE
Adding new provider Legendas.TV - pt-br subtitles

### PR DESCRIPTION
**Pull request by danielsnipher**
Add most used portuguese brazil subtitle provider (Legendas.tv)

### CODE REVIEW

**Comment by pannal** [comment]
You're just a minute too late with your PR. 2.0 will[ have legendas from subliminal 2.0 implemented](https://github.com/Diaoul/subliminal/blob/develop/subliminal/providers/legendastv.py). I will try to merge your changed, though.

**Comment by danielsnipher** [comment]
Great news.
Thanks.

--
Daniel Abreu

Em 22 de abr de 2017 01:23, "pannal" <notifications@github.com> escreveu:

**Comment by guilhermecgs** [comment]
Very useful PR!

**Comment by pannal** [comment]
pt-BR is in SZ 2.0, which is currently in beta. Thank you for the PR!

**Pull request closed without merging**
