### PR TITLE
Add provider assrt.net (Chinese)

### PR DESCRIPTION
**Pull request by dimotsai**
To fix this issue #425:

According to the [API doc](http://assrt.net/api/doc), implement a provider for [assrt.net](https://assrt.net/). It supports both Chinese (Traditional) & Chinese (Simplified) by IETF language tag zh-TW & zh-CN separately. 

Also extended opensubtitles language converter to support Chinese (Traditional), since `zh`  represents Chinese (Simplified) only.

PS. Might be more proper to use zh-Hant & zh-Hans rather than specifying regions?

Thank you for creating Sub-Zero, it is a very useful plugin ❤️
Any suggestions are welcome!

### CODE REVIEW

**Comment by dimotsai** [comment]
Already changed to zh-Hant & zh-Hans

**Comment by pannal** [comment]
OK, one issue here. We can't "insert" new languages into the existing language preferences of SZ, only append them to the end. Otherwise everyone who had a language configured below the one where a new one has been inserted, their language will magically change.

This sadly is a plex addon settings implementation issue and can't be fixed.

Please move the newly added languages to the end of the list until I find a fix for that.

**Comment by dimotsai** [comment]
@pannal Done

**Comment by pannal** [comment]
Thank you!

**Pull request merged**
